version: '3'

services:
  db:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env

    volumes: 
      - "/home/hakahmed/data/db:/var/lib/mysql"
  wp:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    # volumes:
    #   - "/home/hakahmed/data/wordpress:"

volumes:
  database:

