version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env

    volumes: 
      - "/home/hakahmed/data/db:/var/lib/mysql"

    networks:
      - wordpress-mariadb

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env

    networks:
      - wordpress-nginx
      - wordpress-mariadb

    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env

    networks:
      - wordpress-nginx

    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

    depends_on:
      - wordpress
      - adminer

  redis:
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    env_file:
      - .env

    networks:
      - wordpress-nginx

    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

  adminer:
    build: ./requirements/bonus/adminer
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

  vsftpd:
    build: ./requirements/bonus/vsftpd
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"
    ports:
      - "21:21"
    depends_on:
      - wordpress

  grafana:
    build: ./requirements/bonus/grafana
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

    networks:
      - wordpress-mariadb
      - wordpress-nginx

  static-page:
    build: ./requirements/bonus/static-page
    volumes: 
      - "/home/hakahmed/data/grafana:/usr/share/grafana"

networks:
  wordpress-nginx:
  wordpress-mariadb:

volumes:
  database:
  wp:
  grafana:
