version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env

    volumes: 
      - "/home/hakahmed/data/db:/var/lib/mysql"

    networks:
      - wordpress-mariadb

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env

    networks:
      - wordpress-nginx
      - wordpress-mariadb

    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env

    networks:
      - wordpress-nginx

    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

    depends_on:
      - wordpress

networks:
  wordpress-nginx:
  wordpress-mariadb:

volumes:
  database:
  wp:
