version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes: 
      - "/home/hakahmed/data/db:/var/lib/mysql"
    networks:
      - wordpress-mariadb
    restart: always

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"
    networks:
      - wordpress-nginx
      - wordpress-mariadb
      - ftp
    restart: always
    depends_on:
      - mariadb
      - redis

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"
    networks:
      - wordpress-nginx
      - ftp
    restart: always
    depends_on:
      - wordpress

  redis:
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"
    networks:
      - wordpress-nginx
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

  vsftpd:
    build: ./requirements/bonus/vsftpd
    ports:
      - "21:21"
      - "21000-21100:21000-21100"
    env_file:
      - .env
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"
    networks:
      - ftp
    restart: always
    depends_on:
      - wordpress

  grafana:
    build: ./requirements/bonus/grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - wordpress-mariadb
      - wordpress-nginx
    restart: always
    depends_on:
      - mariadb

  static-page:
    build: ./requirements/bonus/static-page
    volumes: 
      - "/home/hakahmed/data/wordpress:/wordpress"

networks:
  wordpress-nginx:
  wordpress-mariadb:
  ftp:

volumes:
  database:
  wp:
  grafana:
