version: '3'

services:
  db:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env

    volumes: 
      - "/home/hakahmed/data:/var/lib/mysql"

volumes:
  database:

